name="Sukanth Kutuwan"
print(name.upper())
print(name.lower())
print(name.capitalize())
print(name.title())
print(name.isalpha())
print(name.isnumeric())
print(name.isalnum)
print(name.isspace())
print(name.istitle())
print(name.isupper())
print(name.replace("S","K"))
# print(name.endswith'an')
# print(name.startswith'n')